# SQLite version 3.x
#   gem install sqlite3
#
#   Ensure the SQLite 3 gem is defined in your Gemfile
#   gem 'sqlite3'
#
default: &default
  adapter: postgresql
  encoding: unicode
  pool: 5
  host: localhost


development:
  <<: *default
  database: spree_multi_domain_dev
  username: toptierlabs
  password:

test:
  <<: *default
  database: spree_multi_domain_test
  username: toptierlabs
  password:

production:
  adapter:  postgresql
  encoding: unicode
  database: spree_multi_domain_prod
  pool: 5
  username: ubuntu
  password:
